version: '3.7'
services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: betting
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
  kafka:
    image: wurstmeister/kafka
    container_name: kafka-container
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "bet_detail:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
    links:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper-container
    ports:
      - "2181:2181"
  app:
    build: .
    container_name: app-container
    ports:
      - "8080:8080"
    depends_on:
      - db
      - kafka
